-- 1. Tabla para el control de gastos por viaje (Diésel, Casetas, Maniobras, etc.)
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_viaje BIGINT REFERENCES viajes(id) ON DELETE CASCADE,
    tipo_gasto TEXT NOT NULL, -- 'Diésel', 'Casetas', 'Taller', 'Otros'
    monto NUMERIC NOT NULL,
    descripcion TEXT,
    fecha DATE DEFAULT CURRENT_DATE
);

-- 2. Tabla para reportes, discrepancias y sanciones de los operadores
CREATE TABLE IF NOT EXISTS incidencias_operadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operador_nombre TEXT NOT NULL, -- Lo ligamos al nombre del chofer
    tipo_reporte TEXT NOT NULL, -- 'Sanción', 'Felicitación', 'Discrepancia'
    descripcion TEXT NOT NULL,
    puntos_record INT DEFAULT -1, -- Descuento en su récord (ej: -1 punto)
    fecha DATE DEFAULT CURRENT_DATE
);

-- Apagamos el RLS para poder meter datos desde la App sin bloqueos
ALTER TABLE gastos DISABLE ROW LEVEL SECURITY;
ALTER TABLE incidencias_operadores DISABLE ROW LEVEL SECURITY;

-- Refrescamos el esquema de la API
NOTIFY pgrst, 'reload schema';
